version: "3.3"
services:
  bot:
    build: .
    restart: always
    environment:
      BOT_TOKEN: "SECRET"
      MEMES_THREAD_ID: "1"
    volumes:
      - "./memes.db:/app/memes.db"
  cron:
    build: .
    entrypoint: "python cron_job.py"
    environment:
      BOT_TOKEN: "SECRET"
      MEMES_THREAD_ID: "1"
    volumes:
      - "./memes.db:/app/memes.db"
